language: emacs-lisp
dist: xenial
env:
  - EMACS=emacs25
before_install:
  - sudo apt-get install -qq autoconf
  - sudo add-apt-repository -y ppa:kelleyk/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS
script:
  autoconf && ./configure && make
notifications:
  slack:
    secure: rFmM+Zj1neGtX2GQKNqNexWJuNe7aBZqjhaf9aSO/9eGSrZs4QVL2UbXMgGRI41CLRdrmqR4z6MJZe6bk843Q2TcWLYOrwcQBele6M0dQFlWRdmKyFzxWtyYQQLR0mACVt102oRxWOajmmXSAhvr3FKFWVM3lDCAFXLEStF5TEHcudObPTTx9Zw+dGIY0UibuaircR8CcvfSIidmh4KsgGrhxIHEwMu90ppx4dEENlXWB5mrS4rMIwVzTqziqD5P75vbBNuzj5sqrKuVmVyPch8Lzvu5eJGTKSI7QXl65BoejB7tWoWDQ7hEqG3LwEPNAFjUlbV/mkJmqk0c5cnpVhBYDpPmVh4n74E6Wzc7HESVVoR+AXKhNsWveV6rjP7zUGwjQ7iIbRms2sbNmhHj1sx7L1khO4FKI3YdsalPrL9RIr7rjuCCW0rG4d1Eewv38sFJSqyR47+QBDg/rAR2klAKlJGx/thyho53iHy/q0ecOp9OmdV6Lv5G4jkSQZvKenJP/5MnJ4JbecONLgG7rw/m+RxCITUtHMnudeCl8QIUI3RTh0Di/6ppbDl043IDMTrGngAuZthwZkjovJCCoS9zkqj+w08CUE415cpUZut21lIkcx0xCVkQ/lYoESLm4BSm37JdgZeiOqCnTvUr+UgKJlPc3XUQwVuC+Y0Qc5Y=
